name: CodeCov

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.8'
    steps:
    - uses: actions/checkout@master

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        conda env update --file environment.yml --name base

    - name: 'generate report'
      run: |
        $CONDA/bin/coverage run -m pytest
        $CONDA/bin/coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: pytest
        fail_ci_if_error: true
